### ISSUE TITLE
Page for accepting donations to our open source project

### ISSUE THREAD

**Issue by nolim1t** [lncm/lncm.github.io#1]
Like all open source project, we should have a donations page (this should go towards hardware, steaks, and eventually subsidizing a hackathon).

Preference for lightning, but also an onchain address (multi-sig!) for those who aren't "reckless" enough.

**Comment by meeDamian** [comment]
Sure, let's generate a multisig bech32 address - cool idea - let's talk more about it on Wire.

As for LN - I am planning on changing [invoicer] in a way that would allow anyone to access it, but it requires adding some things ex. DoS protections, periodic invoice cleanup etc. Once we have that done, we can generate invoices with a specific description (to simplify stats later) and load-balance between all our nodes, alternatively have a dedicated LN node for donations.


[invoicer]: https://github.com/lncm/invoicer

**Comment by nolim1t** [comment]
You can use my static ip LN node.. it’s on a vps which is funded with bitcoin

**Comment by IstoraMandiri** [comment]
What do you think about just having a 'donate' link on each page (in the footer), with a modal to show a bunch of different options / qrcodes?

**Comment by AnotherDroog** [comment]
It would be good also to pre-select different reasonable amounts and tell people about the merch they can get

e.g.
$5 (stickers)
$10 (free T-shirt)
$25 (free hat)
$50 (hat & shirt)

**Comment by meeDamian** [comment]
These amounts should include international shipping, our time to get it shipped, and some left over (it is a donation after all).

**Comment by AnotherDroog** [comment]
Good point, better to increase t-shirt to $15 then
