### ISSUE TITLE
Add donations link to lncm.io

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/lncm.github.io#10]
Donations page will live at par.lncm.io:1666

**Comment by nolim1t** [comment]
This is similar to #1 ?

**Comment by nolim1t** [comment]
See #15 and #16  (Preview pull request).

Will use bottle.li for lightning tips. Amounts  shouldn't be a lot of money and access is only to those who have access to the social media account. Risk is low.

When theres a sizeable amount in there should move it to the multi-sig.
