### ISSUE TITLE
Set up CI script to auto-publish build

### ISSUE THREAD

**Issue by IstoraMandiri** [lncm/lncm.github.io#3]
If we want, we can set up a Travis-CI script to automatically re-build and publish the website, so people only need to edit/add a file and make a pull request (without having to download anything).

**Comment by meeDamian** [comment]
So raw stuff is on master then some CI builds it and (force) pushes to `gh-pages` which are set up as Github Pages source? sounds good to me, (given ex travis can do it?)

**Comment by IstoraMandiri** [comment]
If something gets pushed to `source`, this will trigger travis to rebuild and publish to `master`, which will then publish to https://lncm.github.io

**Comment by meeDamian** [comment]
same-same – cool :)

**Comment by nolim1t** [comment]
Done as of https://github.com/lncm/lncm.github.io/commit/2d01c824287e5c08baab336be1d42569192cdfb9
