### ISSUE TITLE
Write content for lncm web

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/lncm.github.io#4]

**Comment by meeDamian** [comment]
While the content itself is very good, the text just looks like a monotonous wall of text. I think it might make sense to either format it better (make at least headers a bit more pronounced), or change content to something more digestible - the most popular and efficient way to go about it is to highlight 3 most important "bullet points" on the website in an easy to scan and grasp way, but that might be a scope for another issue perhaps? cc. @AnotherDroog @hitchcott

**Comment by AnotherDroog** [comment]
Yes agreed

**Comment by IstoraMandiri** [comment]
Agree with @meeDamian.

What I put together was intended to be a bare minimum code for functionality, with no time spent on style or look and feel.

I would recommend we try to find an aesthetic (by selecting a few different project websites), and riff of that. Please post any suggestions.

**Comment by IstoraMandiri** [comment]
https://www.parity.io/
https://bitcoin.org/en/
https://lightning.network/

**Comment by AnotherDroog** [comment]
I think we should focus more on web UI for the box rather than improving the website too much now.

Of course adding twitter to the site is a good idea

**Comment by AnotherDroog** [comment]
@hitchcott Here's some designs we can use for free, if we're going for the "generic SF startup look"
https://cruip.com

**Comment by IstoraMandiri** [comment]
I like https://demo.cruip.com/florence/

**Comment by AnotherDroog** [comment]
Yeah I also really like that one.

**Comment by AnotherDroog** [comment]
Let's close this issue and make a new one for redesign
