### ISSUE TITLE
Structure Updates

### ISSUE THREAD

**Issue by IstoraMandiri** [lncm/lncm.github.io#6]
- rename 'blog' to 'announcements'
- remove the team section (or do something else with it eventually) 
- someone write a blog post :)

**Comment by meeDamian** [comment]
As for the team page, perhaps you can `GET https://api.github.com/orgs/lncm/members` and do `response.map(({login, html_url, avatar_url}) => "some magical HTML")` with the `response` (although most people are quite shy about being a member of `lncm` 😞)

<img width="109" alt="macos 2018-11-06 at 17 49 31" src="https://user-images.githubusercontent.com/526657/48059668-60f4fd80-e1ec-11e8-9fdf-ff1225a21696.png">

**Comment by IstoraMandiri** [comment]
I've removed _team_ and _blog_  for now...

**Comment by nolim1t** [comment]
org membership is set to private by default
