### ISSUE TITLE
Social Medias

### ISSUE THREAD

**Issue by IstoraMandiri** [lncm/lncm.github.io#8]

**Comment by meeDamian** [comment]
Just to list them all somewhere for reference:

* `@lncnx`: [Twitter]
* `@lncm`: [Github], [Docker Hub], [Gitlab]\(?), [npmjs]
* `@lncm@bitcoinhackers.org`: [Mastodon]

> **Note:** Feel free to edit and add more, if I missed something.

[Twitter]: https://twitter.com/lncnx
[Github]: https://github.com/lncm
[Docker Hub]: https://hub.docker.com/u/lncm/
[Gitlab]: https://gitlab.com/lncm/
[npmjs]: https://www.npmjs.com/org/lncm
[Mastodon]: https://bitcoinhackers.org/@lncm
